name: Deploy to Mac

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull captainbarduck/my-nginx:latest
            docker stop my-nginx || true
            docker rm my-nginx || true
            docker run -d --name my-nginx -p 8080:80 captainbarduck/my-nginx:latest
